/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 0.38.1
 * Product:       stc3x
 * Model-Version: 1.0.0
 */
/*
 * Copyright (c) 2024, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/*
 * For this example you need to install the SHT4x library
 * 'Sensirion I2C SHT4X'.
 * Please find all relevant instructions here:
 * https://github.com/Sensirion/arduino-i2c-sht4x
 */
/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 * Integrated with Software Baseline and Clearance Notification
 */
#include <Arduino.h>
#include <SensirionI2CSht4x.h>
#include <SensirionI2cStc3x.h>
#include <Wire.h> 
#include <bluefruit.h>

#ifdef NO_ERROR
#undef NO_ERROR
#endif
#define NO_ERROR 0

SensirionI2cStc3x stc3x_sensor;
SensirionI2CSht4x sht4x_sensor;
BLEUart bleuart;

static char errorMessage[64];
static int16_t error;
unsigned long clearStartTime = 0; // Stores when the chamber first looked clear
bool isClearing = false;          // Tracks if we are currently in the 10-second countdown
float clearThreshold = 0.10;      // Your target "clear" ppm/percentage

void sendLine (const String& msg)
{
  Serial.println(msg);
  if (Bluefruit.connected())
  {
    bleuart.println (msg);
  }
}
void setupBLE()
{
  Bluefruit.begin();
  Bluefruit.setTxPower(4);
  Bluefruit.setName("STC31-C");

  bleuart.begin();

  startAdv();
}
void startAdv(void)
{
  Bluefruit.Advertising.stop();
  Bluefruit.ScanResponse.addName();
  Bluefruit.Advertising.addFlags(BLE_GAP_ADV_FLAGS_LE_ONLY_GENERAL_DISC_MODE);
  Bluefruit.Advertising.addTxPower();
  Bluefruit.Advertising.addService(bleuart);
  Bluefruit.Advertising.restartOnDisconnect(true);
  Bluefruit.Advertising.setInterval(32, 244);
  Bluefruit.Advertising.setFastTimeout(30);
  Bluefruit.Advertising.start(0);
}

void PrintUint64(uint64_t& value) {
    char buf[20];
    sprintf(buf, "0x%08X%08X", (uint32_t)(value >> 32), (uint32_t)(value & 0xFFFFFFFF));
    sendLine("STC3x Serial: " + String(buf));
}

void setup() {
    Serial.begin(115200);
    while (!Serial) {
        delay(100);
    }
    Wire.begin();
    stc3x_sensor.begin(Wire, STC31_C_I2C_ADDR_29);
    sht4x_sensor.begin(Wire);

    uint32_t stc3xProductId = 0;
    uint64_t stc3xSerialNumber = 0;
    uint32_t sht4xSerialNumber = 0;

    delay(100);

    setupBLE();
    sendLine("ex");

    error = sht4x_sensor.serialNumber(sht4xSerialNumber);
    if (error == NO_ERROR) {
        sendLine("SHT4x Serial: " + String(sht4xSerialNumber));
    }

    error = stc3x_sensor.getProductId(stc3xProductId, stc3xSerialNumber);
    if (error == NO_ERROR) {
        sendLine("STC3x ID: " + String(stc3xProductId));
        PrintUint64(stc3xSerialNumber);
    }

    // Set Binary Gas to Mode 19 (Low-cross-sensitivity for CO2 in Air)
    error = stc3x_sensor.setBinaryGas(19);
    
}

void loop() {
    float stc3xCo2Concentration = 0.0;
    float stc3xTemperature = 0.0;
    float sht4xTemperature = 0.0;
    float sht4xRelativeHumidity = 0.0;

    delay(250); // responsiveness

    // Read SHT4x for compensation
    error = sht4x_sensor.measureHighPrecision(sht4xTemperature, sht4xRelativeHumidity);
    if (error == NO_ERROR) {
        stc3x_sensor.setRelativeHumidity(sht4xRelativeHumidity);
        stc3x_sensor.setTemperature(sht4xTemperature);
    }

    // Measure gas concentration
    error = stc3x_sensor.measureGasConcentration(stc3xCo2Concentration, stc3xTemperature);
    if (error != NO_ERROR) {
        errorToString(error, errorMessage, sizeof errorMessage);
        sendLine("Error: " + String(errorMessage));
        return;
    }


    // 2. Calculate Corrected PPM (Relative to baseline)
    float co2Ppm = stc3xCo2Concentration * 10000.0;

    // 4. Clearance Notification Logic
        // If gas drops below 500ppm and was previously high
float currentCO2 = stc3xCo2Concentration; 

if (currentCO2 <= clearThreshold) {
    if (!isClearing) {
        // This is the first time it dropped below the threshold
        clearStartTime = millis(); 
        isClearing = true;
    }

    // Check if 10,000 milliseconds (10 seconds) have passed
    if (millis() - clearStartTime >= 10000) {
        Serial.println("CHAMBER CONFIRMED CLEAR");
        // Trigger your next step here (e.g., turn off pump, allow next test)
        isClearing = false; 
    }
} 
else {
    // If the CO2 goes above the threshold, reset the timer
    if (isClearing) {
        isClearing = false;
    }
}
    // 5. Printing (Optimized to show status)
    String dataOutput = "T:" + String(stc3xTemperature, 1);
    dataOutput += " H:" + String(sht4xRelativeHumidity, 1);
    dataOutput +=  " CO2%:" + String(stc3xCo2Concentration, 4);
    dataOutput +=  " PPM:" + String(co2Ppm, 0);

    sendLine(dataOutput);
}